// components/discovery/SearchBar.tsx
'use client';

import { useEffect, useRef, useState, useCallback } from 'react';
import { Search, X } from 'lucide-react';
import { v4 as uuidv4 } from 'uuid';
import { useMapStore } from '@/store/map.store';
import { usePOISearch } from '@/hooks/usePOISearch';
import { useLocationStore } from '@/store/location.store';
import { cn } from '@/lib/utils';

interface Suggestion {
  placeId: string;
  text: string;
  secondaryText?: string;
}

export default function SearchBar() {
  const [value, setValue] = useState('');
  const [suggestions, setSuggestions] = useState<Suggestion[]>([]);
  const [isFocused, setIsFocused] = useState(false);
  const sessionTokenRef = useRef(uuidv4());
  const debounceRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const { mapInstance } = useMapStore();
  const { search } = usePOISearch();
  const location = useLocationStore();

  const fetchSuggestions = useCallback(
    async (input: string) => {
      if (input.length < 2) {
        setSuggestions([]);
        return;
      }

      try {
        const body: Record<string, unknown> = {
          input,
          sessionToken: sessionTokenRef.current,
        };
        if (location.coordinates) {
          body.locationBias = location.coordinates;
        }

        const res = await fetch('/api/places/autocomplete', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(body),
        });

        if (res.ok) {
          const data = await res.json();
          setSuggestions(data.suggestions ?? []);
        }
      } catch {
        // ignore search errors
      }
    },
    [location.coordinates],
  );

  useEffect(() => {
    clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => fetchSuggestions(value), 300);
    return () => clearTimeout(debounceRef.current);
  }, [value, fetchSuggestions]);

  const selectSuggestion = async (suggestion: Suggestion) => {
    setValue(suggestion.text);
    setSuggestions([]);
    sessionTokenRef.current = uuidv4(); // Reset session token

    try {
      const res = await fetch(`/api/places/details?placeId=${suggestion.placeId}`);
      if (res.ok) {
        const poi = await res.json();
        if (mapInstance && poi.coordinates) {
          mapInstance.panTo(poi.coordinates);
          mapInstance.setZoom(14);
          search(poi.coordinates, true);
        }
      }
    } catch {
      // ignore
    }
  };

  const clear = () => {
    setValue('');
    setSuggestions([]);
  };

  return (
    <div className="relative flex-1">
      <div
        className={cn(
          'flex items-center gap-2 h-11 px-3 rounded-xl border',
          'bg-[var(--color-surface)] border-[var(--color-border)]',
          isFocused && 'border-[var(--color-accent)]',
        )}
      >
        <Search size={16} className="text-[var(--color-text-muted)] shrink-0" />
        <input
          type="text"
          value={value}
          onChange={(e) => setValue(e.target.value)}
          onFocus={() => setIsFocused(true)}
          onBlur={() => setTimeout(() => setIsFocused(false), 150)}
          placeholder="Search places…"
          className="flex-1 bg-transparent text-[var(--color-text-primary)] placeholder:text-[var(--color-text-muted)] text-sm outline-none"
          aria-label="Search places"
          autoComplete="off"
        />
        {value && (
          <button onClick={clear} aria-label="Clear search" className="text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)]">
            <X size={14} />
          </button>
        )}
      </div>

      {suggestions.length > 0 && isFocused && (
        <ul className="absolute top-full mt-1 left-0 right-0 z-30 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] shadow-xl overflow-hidden">
          {suggestions.map((s) => (
            <li key={s.placeId}>
              <button
                onMouseDown={() => selectSuggestion(s)}
                className="w-full text-left px-3 py-2.5 hover:bg-[var(--color-surface-2)] transition-colors"
              >
                <div className="text-sm text-[var(--color-text-primary)] truncate">{s.text}</div>
                {s.secondaryText && (
                  <div className="text-xs text-[var(--color-text-muted)] truncate">{s.secondaryText}</div>
                )}
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// components/discovery/SearchBar.vue
<script setup>
// Google Places Autocomplete search overlay — Feature 6
// See docs/FEATURES_V1.md#feature-6 and docs/API_INTEGRATIONS.md#server-route-autocomplete

import { useMapStore } from '../../stores/map.store.js'
import { usePOISearch } from '../../composables/usePOISearch.js'

const mapStore = useMapStore()
const { searchNearby } = usePOISearch()

const query = ref('')
const suggestions = ref([])
const sessionToken = ref('')
const isOpen = ref(false)
const inputEl = ref(null)

let debounceTimer = null

function onFocus() {
  sessionToken.value = crypto.randomUUID()
  isOpen.value = true
}

function onBlur() {
  // Delay close so click on suggestion registers first
  setTimeout(() => { isOpen.value = false }, 150)
}

function onClear() {
  query.value = ''
  suggestions.value = []
  isOpen.value = false
  inputEl.value?.focus()
}

async function fetchSuggestions(input) {
  if (input.length < 2) { suggestions.value = []; return }
  const locationBias = mapStore.center
  try {
    const data = await $fetch('/api/places/autocomplete', {
      method: 'POST',
      body: { input, sessionToken: sessionToken.value, locationBias },
    })
    suggestions.value = data.suggestions ?? []
  } catch {
    suggestions.value = []
  }
}

watch(query, (val) => {
  clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => fetchSuggestions(val), 300)
})

async function selectSuggestion(s) {
  query.value = s.text
  suggestions.value = []
  isOpen.value = false

  if (!s.placeId) return

  try {
    const place = await $fetch(`/api/places/details?placeId=${s.placeId}`)
    if (place?.location) {
      mapStore.map?.panTo(place.location)
      mapStore.map?.setZoom(14)
      await searchNearby(place.location)
    }
  } catch { /* swallow — map remains functional */ }
}
</script>

<template>
  <div class="absolute top-4 left-1/2 -translate-x-1/2 w-[90%] max-w-sm z-10">
    <div class="relative flex items-center rounded-2xl shadow-lg"
      style="background:var(--color-surface);border:1px solid var(--color-border);">
      <!-- Search icon -->
      <svg class="absolute left-3 shrink-0 w-4 h-4" style="color:var(--color-text-muted);"
        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>
      </svg>

      <input
        ref="inputEl"
        v-model="query"
        type="text"
        placeholder="Search places…"
        class="w-full py-3 pl-9 pr-9 text-sm bg-transparent outline-none"
        style="color:var(--color-text-primary);"
        autocomplete="off"
        @focus="onFocus"
        @blur="onBlur"
      />

      <!-- Clear button -->
      <button
        v-if="query"
        class="absolute right-3 flex items-center justify-center w-5 h-5 rounded-full"
        style="background:var(--color-surface-2);"
        @click="onClear"
      >
        <svg class="w-3 h-3" style="color:var(--color-text-secondary);"
          viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
          <path d="M18 6 6 18M6 6l12 12"/>
        </svg>
      </button>
    </div>

    <!-- Suggestions dropdown -->
    <ul
      v-if="isOpen && suggestions.length"
      class="mt-1 rounded-2xl overflow-hidden shadow-lg"
      style="background:var(--color-surface);border:1px solid var(--color-border);"
    >
      <li
        v-for="s in suggestions"
        :key="s.placeId"
        class="flex flex-col px-4 py-3 cursor-pointer text-sm"
        style="border-bottom:1px solid var(--color-border);"
        @mousedown.prevent="selectSuggestion(s)"
      >
        <span style="color:var(--color-text-primary);">{{ s.text }}</span>
        <span class="text-xs" style="color:var(--color-text-muted);">{{ s.secondaryText }}</span>
      </li>
    </ul>
  </div>
</template>
