// components/discovery/POICard.tsx
'use client';

import { X, Star, MapPin, Clock, ExternalLink, Plus, Check } from 'lucide-react';
import { toast } from 'sonner';
import type { POI } from '@/types';
import { useItineraryStore } from '@/store/itinerary.store';
import { cn } from '@/lib/utils';

interface Props {
  poi: POI;
  onClose: () => void;
}

export default function POICard({ poi, onClose }: Props) {
  const { itinerary, addStop } = useItineraryStore();
  const isInItinerary = itinerary.stops.some((s) => s.placeId === poi.placeId);

  const handleAdd = () => {
    addStop({
      type: 'poi',
      name: poi.name,
      coordinates: poi.coordinates,
      address: poi.address,
      placeId: poi.placeId,
    });
    toast.success('Added to itinerary');
  };

  const mapsUrl = `https://www.google.com/maps/place/?q=place_id:${poi.placeId}`;

  return (
    <div
      className="absolute bottom-0 left-0 right-0 z-30 md:left-auto md:right-4 md:bottom-4 md:w-96"
      aria-live="polite"
    >
      <div className="bg-[var(--color-surface)] border border-[var(--color-border)] rounded-t-2xl md:rounded-2xl shadow-2xl max-h-[45vh] overflow-y-auto">
        {/* Drag handle (mobile) */}
        <div className="md:hidden flex justify-center pt-3 pb-1">
          <div className="w-10 h-1 rounded-full bg-[var(--color-border)]" />
        </div>

        <div className="p-4">
          <div className="flex items-start justify-between gap-2">
            <div className="flex-1 min-w-0">
              <h2 className="text-base font-semibold text-[var(--color-text-primary)] truncate">{poi.name}</h2>
              <p className="text-sm text-[var(--color-text-secondary)] capitalize">{poi.type.replace(/_/g, ' ')}</p>
            </div>
            <div className="flex items-center gap-2 shrink-0">
              {poi.rating && (
                <span className="flex items-center gap-1 text-sm text-[var(--color-warning)]">
                  <Star size={14} fill="currentColor" />
                  {poi.rating.toFixed(1)}
                  {poi.ratingCount && (
                    <span className="text-[var(--color-text-muted)]">({poi.ratingCount})</span>
                  )}
                </span>
              )}
              <button
                onClick={onClose}
                aria-label="Close"
                className="min-w-[32px] min-h-[32px] flex items-center justify-center rounded-lg text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)] hover:bg-[var(--color-surface-2)]"
              >
                <X size={16} />
              </button>
            </div>
          </div>

          {poi.address && (
            <div className="flex items-center gap-1.5 mt-2 text-sm text-[var(--color-text-secondary)]">
              <MapPin size={14} className="shrink-0" />
              <span className="truncate">{poi.address}</span>
            </div>
          )}

          {poi.openNow !== undefined && (
            <div className="flex items-center gap-1.5 mt-1 text-sm">
              <Clock size={14} className="shrink-0 text-[var(--color-text-muted)]" />
              <span className={poi.openNow ? 'text-[var(--color-success)]' : 'text-[var(--color-error)]'}>
                {poi.openNow ? 'Open now' : 'Closed'}
              </span>
            </div>
          )}

          <div className="flex gap-2 mt-4">
            <button
              onClick={handleAdd}
              disabled={isInItinerary}
              className={cn(
                'flex-1 flex items-center justify-center gap-1.5 h-10 rounded-lg text-sm font-medium transition-colors',
                isInItinerary
                  ? 'bg-[var(--color-surface-2)] text-[var(--color-text-muted)] cursor-default'
                  : 'bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white',
              )}
            >
              {isInItinerary ? <Check size={15} /> : <Plus size={15} />}
              {isInItinerary ? 'In Itinerary' : 'Add to Itinerary'}
            </button>
            <a
              href={mapsUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center gap-1.5 h-10 px-3 rounded-lg text-sm text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] bg-[var(--color-surface-2)] transition-colors"
              aria-label="View in Google Maps"
            >
              <ExternalLink size={15} />
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}

// .claude/worktrees/focused-feistel-748305/components/discovery/POICard.vue
<script setup>
// Info card for a selected POI or byway — Feature 5
// See docs/FEATURES_V1.md#feature-5
//
// Behavior:
//   - Shown when discovery store has a selectedPOI
//   - Bottom sheet on mobile (< 768px), side panel on desktop
//   - Dismissed by tapping map, swiping down, or close button
//   - "Add to Itinerary" adds to itinerary store; shows "In Itinerary" if already added
//   - Max 40% of map height when open

import { useDiscoveryStore } from '../../stores/discovery.store.js'
import { useItinerary } from '../../composables/useItinerary.js'
import { useMapStore } from '../../stores/map.store.js'
import { haversineDistance } from '../../lib/proximity-sort.js'

const discoveryStore = useDiscoveryStore()
const mapStore = useMapStore()
const { hasStop, addStop } = useItinerary()

const poi = computed(() => discoveryStore.selectedPOI)
const isVisible = computed(() => !!poi.value)
const alreadyAdded = computed(() => poi.value && hasStop(poi.value.id))
const isByway = computed(() => poi.value?.types?.includes('byway'))

const distanceMiles = computed(() => {
  if (!poi.value?.location || !mapStore.center) return null
  const d = haversineDistance(mapStore.center, poi.value.location)
  return d < 0.1 ? null : d.toFixed(1)
})

function dismiss() {
  discoveryStore.clearSelection()
}

function handleAdd() {
  if (!alreadyAdded.value) addStop(poi.value)
}

function googleMapsUrl(p) {
  if (!p?.location) return '#'
  return `https://www.google.com/maps/search/?api=1&query=${p.location.lat},${p.location.lng}&query_place_id=${p.id}`
}
</script>

<template>
  <Transition name="slide-up">
    <div
      v-if="isVisible"
      class="absolute bottom-0 left-0 right-0 z-20 md:bottom-auto md:top-4 md:left-auto md:right-4 md:w-80
             max-h-[40vh] overflow-y-auto rounded-t-2xl md:rounded-2xl"
      style="background:var(--color-surface);border:1px solid var(--color-border);"
    >
      <!-- Header -->
      <div class="flex items-start justify-between p-4 pb-2">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium mb-0.5" style="color:var(--color-accent);"
            v-if="poi.types?.length">
            {{ isByway ? 'Scenic Byway' : poi.types[0].replace(/_/g, ' ') }}
          </p>
          <h3 class="text-base font-semibold leading-tight" style="color:var(--color-text-primary);">{{ poi.name }}</h3>
        </div>
        <button
          class="ml-3 p-1.5 rounded-lg shrink-0"
          style="background:var(--color-surface-2);"
          @click="dismiss"
        >
          <svg class="w-4 h-4" style="color:var(--color-text-secondary);"
            viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
            <path d="M18 6 6 18M6 6l12 12"/>
          </svg>
        </button>
      </div>

      <!-- Details -->
      <div class="px-4 pb-4 space-y-1.5">
        <p v-if="poi.address" class="text-sm" style="color:var(--color-text-secondary);">{{ poi.address }}</p>

        <div class="flex items-center gap-3 text-sm" style="color:var(--color-text-secondary);">
          <span v-if="poi.rating">★ {{ poi.rating }}
            <span v-if="poi.userRatingsTotal" class="text-xs" style="color:var(--color-text-muted);"> ({{ poi.userRatingsTotal.toLocaleString() }})</span>
          </span>
          <span v-if="distanceMiles">{{ distanceMiles }} mi away</span>
        </div>

        <p v-if="poi.openNow !== undefined" class="text-sm"
          :style="`color:${poi.openNow ? 'var(--color-success)' : 'var(--color-error)'};`">
          {{ poi.openNow ? 'Open now' : 'Closed' }}
        </p>

        <!-- Byway-specific fields -->
        <template v-if="isByway && poi._byway">
          <p v-if="poi._byway.length_mi" class="text-sm" style="color:var(--color-text-secondary);">{{ poi._byway.length_mi }} miles</p>
          <p v-if="poi._byway.description" class="text-sm" style="color:var(--color-text-secondary);">{{ poi._byway.description }}</p>
          <a v-if="poi._byway.url" :href="poi._byway.url" target="_blank" rel="noopener"
            class="text-sm underline" style="color:var(--color-accent);">Official website ↗</a>
        </template>
      </div>

      <!-- Actions -->
      <div class="flex gap-2 px-4 pb-4">
        <button
          class="flex-1 py-2.5 rounded-xl text-sm font-medium transition-opacity"
          :style="alreadyAdded
            ? 'background:var(--color-surface-2);color:var(--color-text-muted);'
            : 'background:var(--color-accent);color:white;'"
          :disabled="alreadyAdded"
          @click="handleAdd"
        >
          {{ alreadyAdded ? 'In Itinerary' : 'Add to Itinerary' }}
        </button>
        <a
          :href="googleMapsUrl(poi)"
          target="_blank"
          rel="noopener"
          class="flex items-center justify-center px-3 py-2.5 rounded-xl text-sm font-medium"
          style="background:var(--color-surface-2);color:var(--color-text-secondary);border:1px solid var(--color-border);"
        >
          Maps ↗
        </a>
      </div>
    </div>
  </Transition>
</template>

<style scoped>
.slide-up-enter-active, .slide-up-leave-active { transition: transform 0.25s ease, opacity 0.25s ease; }
.slide-up-enter-from, .slide-up-leave-to { transform: translateY(100%); opacity: 0; }
@media (min-width: 768px) {
  .slide-up-enter-from, .slide-up-leave-to { transform: translateY(0) scale(0.95); }
}
</style>
