// pages/share/[encoded].vue
<script setup>
// Read-only shared itinerary view — Feature 9
// See docs/FEATURES_V1.md#feature-9

import { decodeItinerary } from '../../lib/url-encoding.js'

const route = useRoute()

const stops = ref([])
const decodeError = ref(false)

onMounted(() => {
  try {
    const decoded = decodeItinerary(route.params.encoded)
    if (Array.isArray(decoded)) {
      stops.value = decoded
    } else {
      decodeError.value = true
    }
  } catch {
    decodeError.value = true
  }
})

useHead({
  title: computed(() =>
    stops.value.length
      ? `Itinerary — ${stops.value.length} stop${stops.value.length !== 1 ? 's' : ''} — PathWeaver`
      : 'Shared Itinerary — PathWeaver'
  ),
})
</script>

<template>
  <div
    class="min-h-dvh flex flex-col"
    style="background:var(--color-bg);color:var(--color-text-primary);"
  >
    <!-- Header -->
    <header
      class="flex items-center gap-3 px-4 py-4 border-b"
      style="border-color:var(--color-border);"
    >
      <NuxtLink to="/" class="text-sm" style="color:var(--color-accent);">← Map</NuxtLink>
      <h1 class="text-base font-semibold">Shared Itinerary</h1>
    </header>

    <!-- Error state -->
    <div v-if="decodeError" class="flex flex-col items-center justify-center flex-1 px-6 text-center">
      <svg class="w-12 h-12 mb-4" style="color:var(--color-text-muted);"
        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
        <circle cx="12" cy="12" r="10"/>
        <line x1="12" y1="8" x2="12" y2="12"/>
        <line x1="12" y1="16" x2="12.01" y2="16"/>
      </svg>
      <p class="text-base font-medium mb-1" style="color:var(--color-text-primary);">Link is invalid or expired</p>
      <p class="text-sm" style="color:var(--color-text-secondary);">This URL could not be decoded. The link may be incomplete or corrupted.</p>
      <NuxtLink
        to="/"
        class="mt-6 px-5 py-2.5 rounded-xl text-sm font-medium"
        style="background:var(--color-accent);color:white;"
      >
        Open PathWeaver
      </NuxtLink>
    </div>

    <!-- Stop list -->
    <main v-else class="flex-1 px-4 py-6 max-w-xl mx-auto w-full">
      <p class="text-sm mb-4" style="color:var(--color-text-secondary);">
        {{ stops.length }} stop{{ stops.length !== 1 ? 's' : '' }}
      </p>

      <ol class="flex flex-col gap-3">
        <li
          v-for="(stop, i) in stops"
          :key="stop.id"
          class="flex items-start gap-3 p-4 rounded-2xl"
          style="background:var(--color-surface);border:1px solid var(--color-border);"
        >
          <!-- Number badge -->
          <div
            class="shrink-0 w-7 h-7 rounded-full flex items-center justify-center text-sm font-bold mt-0.5"
            style="background:var(--color-accent);color:white;"
          >
            {{ i + 1 }}
          </div>

          <!-- Details -->
          <div class="flex-1 min-w-0">
            <p class="font-medium text-sm" style="color:var(--color-text-primary);">{{ stop.name }}</p>
            <p v-if="stop.address" class="text-xs mt-0.5 truncate" style="color:var(--color-text-muted);">{{ stop.address }}</p>
            <p
              v-if="stop.fieldNote"
              class="text-xs mt-1.5 italic"
              style="color:var(--color-text-secondary);"
            >
              {{ stop.fieldNote }}
            </p>
          </div>

          <!-- Open in Maps -->
          <a
            v-if="stop.location"
            :href="`https://www.google.com/maps/search/?api=1&query=${stop.location.lat},${stop.location.lng}`"
            target="_blank"
            rel="noopener"
            class="shrink-0 p-1.5 rounded-lg mt-0.5"
            style="color:var(--color-accent);"
          >
            <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>
              <polyline points="15 3 21 3 21 9"/>
              <line x1="10" y1="14" x2="21" y2="3"/>
            </svg>
          </a>
        </li>
      </ol>

      <!-- Navigate all CTA -->
      <a
        v-if="stops.length > 1"
        :href="`https://www.google.com/maps/dir/${stops.map(s => `${s.location.lat},${s.location.lng}`).join('/')}`"
        target="_blank"
        rel="noopener"
        class="mt-6 flex items-center justify-center gap-2 w-full py-3 rounded-xl text-sm font-medium"
        style="background:var(--color-accent);color:white;"
      >
        Open full route in Google Maps ↗
      </a>
    </main>
  </div>
</template>

// app/share/[encoded]/page.tsx
import type { Metadata } from 'next';
import Link from 'next/link';
import { decodeItinerary } from '@/lib/url-encoding';
import type { SharedItinerary } from '@/types';
import { MapPin, ExternalLink } from 'lucide-react';

interface Props {
  params: Promise<{ encoded: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { encoded } = await params;
  const itinerary = decodeItinerary(decodeURIComponent(encoded));
  return {
    title: itinerary?.name ? `${itinerary.name} — PathWeaver` : 'Shared Route — PathWeaver',
  };
}

export default async function SharePage({ params }: Props) {
  const { encoded } = await params;
  let itinerary: SharedItinerary | null = null;

  try {
    itinerary = decodeItinerary(decodeURIComponent(encoded));
  } catch {
    itinerary = null;
  }

  if (!itinerary || !itinerary.stops) {
    return (
      <div className="min-h-dvh bg-[#020617] flex items-center justify-center p-6">
        <div className="text-center">
          <h1 className="text-xl font-semibold text-[#f8fafc] mb-2">Link not found</h1>
          <p className="text-[#94a3b8] text-sm mb-6">This link may be invalid or expired.</p>
          <Link href="/" className="text-[#3b82f6] hover:underline text-sm">
            Open PathWeaver →
          </Link>
        </div>
      </div>
    );
  }

  const stops = itinerary.stops;
  const stopCount = stops.length;

  const googleMapsUrl = (() => {
    if (stopCount === 0) return null;
    if (stopCount === 1) {
      const s = stops[0];
      return `https://www.google.com/maps/search/?api=1&query=${s.coordinates.lat},${s.coordinates.lng}`;
    }
    const origin = `${stops[0].coordinates.lat},${stops[0].coordinates.lng}`;
    const dest = `${stops[stopCount - 1].coordinates.lat},${stops[stopCount - 1].coordinates.lng}`;
    const waypoints = stops
      .slice(1, -1)
      .map((s) => `${s.coordinates.lat},${s.coordinates.lng}`)
      .join('|');
    return `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${dest}${waypoints ? `&waypoints=${waypoints}` : ''}`;
  })();

  return (
    <div className="min-h-dvh bg-[#020617] text-[#f8fafc]">
      <div className="max-w-2xl mx-auto px-4 py-8">
        <div className="mb-6">
          <p className="text-sm text-[#94a3b8] mb-1">PathWeaver</p>
          <h1 className="text-xl font-semibold">
            {itinerary.name ?? 'Shared Route'}
          </h1>
          <p className="text-sm text-[#94a3b8] mt-1">
            {stopCount} stop{stopCount !== 1 ? 's' : ''}
          </p>
        </div>

        {/* Static map placeholder */}
        <div className="rounded-xl overflow-hidden border border-[#334155] mb-6 aspect-video bg-[#0f172a] flex items-center justify-center">
          <p className="text-sm text-[#475569]">Map preview</p>
        </div>

        {/* Stop list */}
        <ol className="space-y-4 mb-8">
          {stops.map((stop, idx) => (
            <li key={stop.id} className="flex gap-3">
              <span className="shrink-0 w-7 h-7 rounded-full bg-[#3b82f6] text-white text-sm font-bold flex items-center justify-center mt-0.5">
                {idx + 1}
              </span>
              <div className="flex-1 min-w-0">
                <p className="font-medium text-[#f8fafc]">{stop.name}</p>
                {stop.address && (
                  <div className="flex items-center gap-1 text-sm text-[#94a3b8] mt-0.5">
                    <MapPin size={12} />
                    <span>{stop.address}</span>
                  </div>
                )}
                {stop.fieldNote && (
                  <p className="text-sm italic text-[#94a3b8] mt-1">&ldquo;{stop.fieldNote}&rdquo;</p>
                )}
              </div>
            </li>
          ))}
        </ol>

        {googleMapsUrl && (
          <a
            href={googleMapsUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 h-11 px-6 rounded-lg bg-[#3b82f6] hover:bg-[#2563eb] text-white text-sm font-medium transition-colors"
          >
            <ExternalLink size={16} />
            Open in Google Maps
          </a>
        )}

        <p className="mt-8 text-xs text-[#475569]">Built with PathWeaver</p>
      </div>
    </div>
  );
}
