// components/itinerary/FieldNoteInput.tsx
'use client';

import { useState } from 'react';
import type { Stop } from '@/types';
import { useItineraryStore } from '@/store/itinerary.store';

interface Props {
  stop: Stop;
}

export default function FieldNoteInput({ stop }: Props) {
  const { updateFieldNote } = useItineraryStore();
  const [editing, setEditing] = useState(false);

  if (!editing && !stop.fieldNote) {
    return (
      <button
        onClick={() => setEditing(true)}
        className="text-xs text-[var(--color-text-muted)] hover:text-[var(--color-accent)] mt-1"
      >
        + Add a note
      </button>
    );
  }

  return (
    <div className="mt-1">
      {editing || stop.fieldNote ? (
        <textarea
          defaultValue={stop.fieldNote ?? ''}
          maxLength={280}
          autoFocus={editing}
          onFocus={() => setEditing(true)}
          onBlur={(e) => {
            updateFieldNote(stop.id, e.target.value);
            setEditing(false);
          }}
          onChange={(e) => updateFieldNote(stop.id, e.target.value)}
          placeholder="Add a note…"
          rows={2}
          className="w-full text-xs italic text-[var(--color-text-secondary)] bg-[var(--color-surface-2)] border border-[var(--color-border)] rounded px-2 py-1 resize-none outline-none focus:border-[var(--color-accent)]"
          aria-label="Field note"
        />
      ) : (
        <p className="text-xs italic text-[var(--color-text-secondary)] mt-0.5">
          &ldquo;{stop.fieldNote}&rdquo;
        </p>
      )}
    </div>
  );
}

// .claude/worktrees/focused-feistel-748305/components/itinerary/FieldNoteInput.vue
<script setup>
// Inline text annotation for a stop — Feature 8
// See docs/FEATURES_V1.md#feature-8
//
// Behavior:
//   - "Add note" tap reveals textarea (max 280 chars)
//   - Saves immediately on input (no save button)
//   - Note is included in share URL and shown in read-only share view

import { useItineraryStore } from '../../stores/itinerary.store.js'

const props = defineProps({
  stopId: { type: String, required: true },
  note: { type: String, default: '' },
})

const store = useItineraryStore()
const isExpanded = ref(!!props.note)
const localNote = ref(props.note)

function onInput() {
  store.updateFieldNote(props.stopId, localNote.value)
}
</script>

<template>
  <div>
    <button v-if="!isExpanded" @click="isExpanded = true" class="text-sm text-accent">
      + Add note
    </button>
    <textarea
      v-else
      v-model="localNote"
      maxlength="280"
      rows="2"
      class="w-full bg-surface text-white text-sm rounded p-2 resize-none"
      placeholder="Add a note…"
      @input="onInput"
    />
  </div>
</template>
