// components/map/BywayLayer.vue
<script setup>
// Renders scenic byway polylines from GeoJSON — Feature 4
// See docs/FEATURES_V1.md#feature-4 and docs/ARCHITECTURE.md#byway-rendering

import { useMapStore } from '../../stores/map.store.js'
import { useDiscoveryStore } from '../../stores/discovery.store.js'
import { useByways } from '../../composables/useByways.js'

const mapStore = useMapStore()
const discoveryStore = useDiscoveryStore()
const { byways, isLoaded } = useByways()

/** @type {google.maps.Polyline[]} */
let polylines = []

function clearPolylines() {
  polylines.forEach((p) => p.setMap(null))
  polylines = []
}

function renderPolylines() {
  if (!mapStore.map || !byways.value) return
  clearPolylines()

  const google = window.google
  const isVisible = mapStore.isBywaysVisible && mapStore.zoom >= 7

  for (const feature of byways.value.features) {
    const color = feature.properties?.color ?? '#3b82f6'
    const geomType = feature.geometry.type
    const coordSets =
      geomType === 'MultiLineString'
        ? feature.geometry.coordinates
        : [feature.geometry.coordinates]

    for (const coords of coordSets) {
      const path = coords.map(([lng, lat]) => ({ lat, lng }))
      const polyline = new google.maps.Polyline({
        path,
        map: mapStore.map,
        strokeColor: color,
        strokeWeight: 4,
        strokeOpacity: 0.8,
        visible: isVisible,
        clickable: true,
      })

      polyline.addListener('click', (e) => {
        discoveryStore.selectPOI({
          id: feature.properties.id,
          name: feature.properties.name,
          location: { lat: e.latLng.lat(), lng: e.latLng.lng() },
          address: feature.properties.state
            ? `${feature.properties.state} Scenic Highway`
            : undefined,
          types: ['byway'],
          _byway: feature.properties,
        })
      })

      polyline.addListener('mouseover', () => {
        polyline.setOptions({ strokeWeight: 6, strokeOpacity: 1.0 })
      })
      polyline.addListener('mouseout', () => {
        polyline.setOptions({ strokeWeight: 4, strokeOpacity: 0.8 })
      })

      polylines.push(polyline)
    }
  }
}

// Render once both map and GeoJSON are ready
watch(
  [() => mapStore.map, isLoaded],
  ([map, loaded]) => { if (map && loaded) renderPolylines() },
  { immediate: true },
)

// Toggle all polylines when layer switch or zoom changes
watch(
  [() => mapStore.isBywaysVisible, () => mapStore.zoom],
  ([visible, zoom]) => {
    const show = visible && zoom >= 7
    polylines.forEach((p) => p.setVisible(show))
  },
)

onUnmounted(() => clearPolylines())
</script>

<template>
  <span hidden aria-hidden="true" />
</template>

// components/map/BywayLayer.tsx
'use client';

import { useEffect, useRef } from 'react';
import type { Feature, LineString, MultiLineString, GeoJsonProperties } from 'geojson';
import { useMapStore } from '@/store/map.store';
import { useDiscoveryStore } from '@/store/discovery.store';
import { useByways } from '@/hooks/useByways';
import type { BywayProperties } from '@/types';

export default function BywayLayer() {
  const { mapInstance, bywaysVisible } = useMapStore();
  const { selectByway } = useDiscoveryStore();
  const byways = useByways();
  const polylinesRef = useRef<google.maps.Polyline[]>([]);

  useEffect(() => {
    if (!mapInstance || !byways) return;

    // Clear existing polylines
    polylinesRef.current.forEach((p) => p.setMap(null));
    polylinesRef.current = [];

    byways.features.forEach((feature: Feature<GeoJSON.Geometry, GeoJsonProperties>) => {
      const props = feature.properties as BywayProperties;
      const color = props.color ?? '#4A90D9';

      const getPath = (coords: number[][]): google.maps.LatLngLiteral[] =>
        coords.map(([lng, lat]) => ({ lat, lng }));

      let paths: google.maps.LatLngLiteral[][] = [];

      if (feature.geometry.type === 'LineString') {
        paths = [getPath((feature as Feature<LineString>).geometry.coordinates)];
      } else if (feature.geometry.type === 'MultiLineString') {
        paths = (feature as Feature<MultiLineString>).geometry.coordinates.map(getPath);
      }

      paths.forEach((path) => {
        const polyline = new google.maps.Polyline({
          path,
          strokeColor: color,
          strokeWeight: 4,
          strokeOpacity: 0.8,
          map: bywaysVisible ? mapInstance : null,
          clickable: true,
        });

        polyline.addListener('click', () => selectByway(props.id));
        polyline.addListener('mouseover', () => {
          polyline.setOptions({ strokeWeight: 6, strokeOpacity: 1 });
        });
        polyline.addListener('mouseout', () => {
          polyline.setOptions({ strokeWeight: 4, strokeOpacity: 0.8 });
        });

        polylinesRef.current.push(polyline);
      });
    });

    return () => {
      polylinesRef.current.forEach((p) => p.setMap(null));
      polylinesRef.current = [];
    };
  }, [mapInstance, byways]); // eslint-disable-line react-hooks/exhaustive-deps

  // Toggle visibility
  useEffect(() => {
    polylinesRef.current.forEach((p) =>
      p.setMap(bywaysVisible ? mapInstance : null),
    );
  }, [bywaysVisible, mapInstance]);

  return null;
}
